apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - name: game-service
        image: australia-southeast1-docker.pkg.dev/cloud-trivia-proj/myrepo/game-service
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: ClusterIP
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
