apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - name: player-service
        image: australia-southeast1-docker.pkg.dev/cloud-trivia-476202/REPO_NAME/player-service:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  type: ClusterIP
  selector:
    app: player-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
