apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: australia-southeast1-docker.pkg.dev/cloud-trivia-proj/myrepo/user-service:latest
        ports:
        - containerPort: 8003
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@user-db-service:5432/users_db
          - name: PORT
            value: "8003"    # ✅ ensures FastAPI/Uvicorn binds to the right port
        readinessProbe:      # ✅ ensures service only becomes “Ready” when it’s actually running
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:       # ✅ restarts container if it freezes
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
